XCODE_LOCATION=/Applications/Xcode.app
MD_FRAMEWORK_LOCATION=/Library/Apple/System/Library/PrivateFrameworks
ifeq ($(wildcard $(MD_FRAMEWORK_LOCATION)/.),)
    MD_FRAMEWORK_LOCATION=/System/Library/PrivateFrameworks
endif

all: clean init built nodebug sign

built:
	g++ -DIOS_DEPLOY_FEATURE_DEVELOPER_MODE -DNDEBUG -arch arm64 -arch x86_64 -mmacosx-version-min=10.13 -isysroot $(XCODE_LOCATION)/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o bin/iosinstall -framework Foundation -framework CoreFoundation -framework MobileDevice -F$(XCODE_LOCATION)/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks -F$(MD_FRAMEWORK_LOCATION) ios-deploy.m

nodebug:
	strip bin/iosinstall

sign:
	codesign -f -s - --en ios-deploy.ent bin/iosinstall

init:
	mkdir -p bin
	awk '{ print "\""$$0"\\n\""}' lldb.py >> lldb.py.h

clean:
	rm -rf bin
	rm -rf lldb.py.h
	rm -rf *.o
